# https://github.com/elastic/elasticsearch-docker
FROM docker.elastic.co/elasticsearch/elasticsearch-platinum:6.2.2

ENV ELASTIC_PASSWORD=supersecret

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
